# Site settings
title: Your Site Title
description: Your site description
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

# Exclude directories and/or files from the conversion
exclude:
  - node_modules
  - server/node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
